version: 2
jobs:
  build:
    docker:
      - image: openjdk:8
    environment:
      SBT_VERSION: 1.0.4
      SBT_OPTS: "-Xms4g"
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run:
          name: Get sbt binary
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get install -y sbt python-pip git
            pip install awscli
            apt-get clean && apt-get autoclean
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: sbt-cache
      - run:
          name: Compile and test
          command: cat /dev/null | sbt clean compile test
  deploy:
    machine: true
    steps:
      - checkout
      - run: |
          docker build --rm=false -t eu.gcr.io/${GOOGLE_PROJECT_ID}/odinson:$CIRCLE_SHA1 .
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud docker -- push eu.gcr.io/${GOOGLE_PROJECT_ID}/odinson:$CIRCLE_SHA1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
